---
- name: Setup Ansible Automation Platform Controller server.
    Pre-load with projects, job templates, and credentials for demo-ing right out of the box.
  hosts: automationcontroller
  become: true
  tasks:

 # vars:
 #   credential_name: "my_new_credential"
 #   credential_description: "A credential for testing"
 #   credential_type: "machine" # Or "vault", "cloud", etc.
 #   credential_username: "IBMUSER"
  #  credential_password: "MY PASS PHRASE1" # Or use "ask" for prompting during execution
  #  credential_organization: "Default"


    - name: Create Machine credential for zos_host's SSH key.
      tags: inventory, hosts, credential, credentials, zos_host
      ansible.controller.credential:
        name: "testmax"
        credential_type: Machine
        organization: Default
        description: "TEST Private SSH key on Controller for connecting to z/OS host."
        inputs:
          username: "asdfa"
        validate_certs: false
        
    - name: Create the credential
      awx.awx.credential:
        name: "{{ credential_name }}"
        description: "{{ credential_description }}"
        credential_type: "{{ credential_type }}"
        inputs:
          username: "{{ credential_username }}"
          password: "{{ credential_password }}"
        organization: "{{ credential_organization }}"
        state: present
