---
- name: Define z/OSMF Software Instances
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    zmf_host: "{{ ansible_host }}"
    zmf_port: 10443
    zmf_user: IBMUSER
    #zmf_password: 'MY PASS PHRASE'
      
  tasks:

    - name: generate random string
      ansible.builtin.set_fact:
        zmf_password: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_numeric=2, length=10) }}"
      no_log: true
      
    - name: Execute the command(s) and return output.
      ibm.ibm_zos_core.zos_tso_command:
        commands:
          - "ALTUSER IBMUSER PHRASE('{{ zmf_password }}') NOEXPIRE RESUME"


    - name: Define Db2_v12 software instance
      ansible.builtin.uri:
        url: "https://{{ zmf_host }}:10443/zosmf/swmgmt/swi"
        method: POST
        user: "{{ zmf_user | trim }}"
        password: "{{ zmf_password | trim }}"
        force_basic_auth: true
        body_format: json
        body:
          name: "Db2_v12"
          system: "VS01_004"
          globalzone: "SMPE.PROGPROD.CSI"
          targetzones: ["DB2V12T"]    
        headers:
          Host: "{{ zmf_host }}"
          Origin: "https://{{ zmf_host }}"
        validate_certs: false
        return_content: true
        status_code: "200"
      register: instance_data
      delegate_to: localhost
      ignore_errors: false

    - name: Define Db2_v13 software instance
      ansible.builtin.uri:
        url: "https://{{ zmf_host }}:10443/zosmf/swmgmt/swi"
        method: POST
        user: "{{ zmf_user | trim }}"
        password: "{{ zmf_password | trim }}"
        force_basic_auth: true
        body_format: json
        body:
          name: "Db2_v13"
          system: "VS01_004"
          globalzone: "SMPE.PROGPROD.CSI"
          targetzones: ["DB2V13T"]    
        headers:
          Host: "{{ zmf_host }}"
          Origin: "https://{{ zmf_host }}"
        validate_certs: false
        return_content: true
        status_code: "200"
      register: instance_data
      delegate_to: localhost
      ignore_errors: false
      
    - name: Define CICS software instance
      ansible.builtin.uri:
        url: "https://{{ zmf_host }}:10443/zosmf/swmgmt/swi"
        method: POST
        user: "{{ zmf_user | trim }}"
        password: "{{ zmf_password | trim }}"
        force_basic_auth: true
        body_format: json
        body:
          name: "CICS"
          system: "VS01_004"
          globalzone: "SMPE.PROGPROD.CSI"
          targetzones: ["CICS61T"]    
        headers:
          Host: "{{ zmf_host }}"
          Origin: "https://{{ zmf_host }}"
        validate_certs: false
        return_content: true
        status_code: "200"
      register: instance_data
      delegate_to: localhost
      ignore_errors: false


