---
- name: Generate random string
  hosts: localhost
  gather_facts: true
  
  tasks:
  
    - name: generate random string
      ansible.builtin.set_fact:
        passphrase: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_numeric=2, length=10) }}"
      no_log: true
      
- name: Execute one or more TSO commands.
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  tasks:

    - name: Execute the command(s) and return output.
      ibm.ibm_zos_core.zos_tso_command:
        commands:
          - "

    - name: Define certificates to RACF
      ibm.ibm_zos_core.zos_tso_command:
        commands:
          - "RACDCERT ID(IBMUSER) ADD('IBMUSER.COMMON.SHOPZ') WITHLABEL('SMPE Client Certificate') PASSWORD('{{ user_password }}') TRUST"
          - RACDCERT CERTAUTH ADD('IBMUSER.COMMON.G2CERT') WITHLABEL('DigiCert Global Root G2') TRUST
          - RACDCERT CERTAUTH ADD('IBMUSER.COMMON.DIGICA') WITHLABEL('DigiCert Global Root CA') TRUST
