---
- name: Generate random string
  hosts: localhost
  gather_facts: true
  
  tasks:
  
    - name: generate random string
      ansible.builtin.set_fact:
        passphrase: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_numeric=2, length=10) }}"
      no_log: true
      
- name: Execute one or more TSO commands.
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  tasks:

    - name: Execute the command(s) and return output.
      ibm.ibm_zos_core.zos_tso_command:
        commands:
          - "ALTUSER IBMUSER PHRASE('{{ passphrase }}') NOEXPIRE RESUME"
