---
- name: List exisiting software instances
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    #zmf_host: itzvsi-zos-pejjzea.techzone.ibm.com
    zmf_host: "{{ ansible_host }}"
    zmf_port: 10443
    zmf_user: IBMUSER

  tasks:

    - name: generate random string
      ansible.builtin.set_fact:
        passphrase: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_numeric=2, length=10) }}"
      no_log: true
      
    - name: Execute the command(s) and return output.
      ibm.ibm_zos_core.zos_tso_command:
        commands:
          - "ALTUSER IBMUSER PHRASE('{{ passphrase }}') NOEXPIRE RESUME"
          
    - name: Get zosmf software instances
      ansible.builtin.uri:
        url: "https://{{ zmf_host }}:10443/zosmf/swmgmt/swi"
        method: GET
        user: "{{ zmf_user | trim }}"
        password: "{{ passphrase | trim }}"
        force_basic_auth: true
        headers:
          Host: "{{ zmf_host }}"
          Origin: "https://{{ zmf_host }}"
        status_code: "200"
        validate_certs: false
        return_content: true
      register: instance_data
      delegate_to: localhost

    - ansible.builtin.set_fact:
        swi_list: '{{ instance_data.json.swilist }}'


    - name: Print json data to terminal for visual verification.
      ansible.builtin.debug:
        msg: "{{ instance_data.json.swilist }}"
