---
- name: List exisiting software instances
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    #zmf_host: itzvsi-zos-pejjzea.techzone.ibm.com
    zmf_host: "{{ ansible_host }}"
    zmf_port: 10443
    zmf_user: IBMUSER
    zmf_password: 'MY PASS PHRASE'

  tasks:

    - name: generate random string
      ansible.builtin.debug:
        var: lookup('community.general.random_string', min_lower=1, min_upper=1, min_numeric=2, length=10)
