---
- name: Generate random string
  hosts: localhost
  gather_facts: true
  
  tasks:
  
    - name: generate random string
      ansible.builtin.set_fact:
        passphrase: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_numeric=2, length=10) }}"
      no_log: true
      
