---
- name: List exisiting software instances
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    #zmf_host: itzvsi-zos-pejjzea.techzone.ibm.com
    zmf_host: "{{ ansible_host }}"
    zmf_port: 10443
    zmf_user: IBMUSER
    zmf_password: "{{ ansible_pass }}"
    user_id: "{{ ibmuser }}"
    password: "{{ my pass phrase }}"

  tasks:
    - name: modify host variable
      ansible.builtin.set_fact:
        ansible_pass: "MY NEW PASS PHRASE'

    - name: Do something with the credentials
      debug:
        msg: "Username: {{ user_id }}, Password: {{ password }}"

        

    - name: Access a vault secret
      ansible.builtin.debug:
        msg: "Vault secret: {{ lookup('ansible.builtin.vault', 'TESTVAULT') }}"

        
    - name: Get zosmf software instances
      ansible.builtin.uri:
        url: "https://{{ zmf_host }}:10443/zosmf/swmgmt/swi"
        method: GET
        user: "{{ zmf_user | trim }}"
        password: "{{ zmf_password | trim }}"
        force_basic_auth: true
        headers:
          Host: "{{ zmf_host }}"
          Origin: "https://{{ zmf_host }}"
        status_code: "200"
        validate_certs: false
        return_content: true
      register: instance_data
      delegate_to: localhost

    - ansible.builtin.set_fact:
        swi_list: '{{ instance_data.json.swilist }}'


    - name: Print json data to terminal for visual verification.
      ansible.builtin.debug:
        msg: "{{ instance_data.json.swilist }}"
